[package]
name = "zanzibar"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
chrono = "0.4.23"
csv = "1.2.1"
image = "0.25.2"
imageproc = "0.25.0"
mouse-rs = "0.4.1"
ndarray = "0.15.6"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta"
