[package]
name = "recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
mouse-rs = "0.4.1"
chrono = "0.4.23"
csv = "1.2.1"
clap = "3.2.23"
video-rs = "0.8.1"
ndarray = "0.15.6"
image = "0.25.2"
rand = "0.8.5"
imageproc = "0.25.0"
winit = "0.30.4"
